name: Wyoming Silero TTS
version: "1.3.0"
slug: wyoming_silero_tts
description: Silero v5 Russian text-to-speech on CPU (Wyoming protocol)
url: https://github.com/ganiushin/parakeet-stt-silero-tts-addons-haos
arch:
  - amd64
  - aarch64
init: false
startup: application
boot: auto
hassio_api: true
discovery:
  - wyoming
ports:
  10200/tcp: 10200
ports_description:
  10200/tcp: Wyoming protocol server
options:
  voice: ru_zhadyra
  sample_rate: "48000"
  threads: 2
  transliterate: true
schema:
  voice: list(ru_zhadyra|ru_zhazira|ru_aigul|ru_albina|ru_alexandr|ru_alfia|ru_alfia2|ru_bogdan|ru_dmitriy|ru_eduard|ru_ekaterina|ru_gamat|ru_igor|ru_karina|ru_kejilgan|ru_kermen|ru_marat|ru_miyau|ru_nurgul|ru_oksana|ru_onaoy|ru_ramilia|ru_roman|ru_safarhuja|ru_saida|ru_sibday|ru_vika|ru_zara|ru_zinaida)
  sample_rate: list(48000|24000|8000)
  threads: int(1,8)
  transliterate: bool
